#docker-compose file for Jenkins and remote-host(has Docker file)

version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    ports:
      - 8080:8080
      - 50000:50000
    privileged: true
    user: root
    volumes:
      - /root/jenkins/jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - net
  remote-host:
    container_name: remote-host
    image: remote-host
    build:
     context: ubuntu
    networks:
       - net
networks:
  net:

  

#chown 1000:1000 jenkins_home -R   this will give ownership permission to jenkins user to access this folder
