version: '3'
services:
	jenkins:
		container_name: jenkins
		image:jenkins/jenkins:lts
		ports:
			- "8008:8008"
		volumes:
			- "/root/jenkins:/var/jenkins_home"
		networks:
		 - net
networks:
	net:
