version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    ports:
      - 8080:8080
    volumes:
      - /root/jenkins/jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
#    networks:
#      - net
#networks:
#  net:

  

#chown 1000:1000 jenkins_home -R   this will give ownership permission to jenkins user to access this folder
